# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dispatcher_admin_pb2 as dispatcher__admin__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatcher_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatcherAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLoop = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StartLoop',
                request_serializer=dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.PauseLoop = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/PauseLoop',
                request_serializer=dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ResumeLoop = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/ResumeLoop',
                request_serializer=dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopLoop = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StopLoop',
                request_serializer=dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ConfirmLoop = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/ConfirmLoop',
                request_serializer=dispatcher__admin__pb2.ConfirmLoopRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopRound = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StopRound',
                request_serializer=dispatcher__admin__pb2.RoundCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopStep = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StopStep',
                request_serializer=dispatcher__admin__pb2.StepCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopJob = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StopJob',
                request_serializer=dispatcher__admin__pb2.JobCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopTask = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/StopTask',
                request_serializer=dispatcher__admin__pb2.TaskCommandRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.TriggerDispatch = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/TriggerDispatch',
                request_serializer=dispatcher__admin__pb2.TriggerDispatchRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetRuntimeSummary = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/GetRuntimeSummary',
                request_serializer=dispatcher__admin__pb2.RuntimeSummaryRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.RuntimeSummaryResponse.FromString,
                _registered_method=True)
        self.GetExecutor = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/GetExecutor',
                request_serializer=dispatcher__admin__pb2.ExecutorReadRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.ExecutorReadResponse.FromString,
                _registered_method=True)
        self.ListExecutors = channel.unary_unary(
                '/saki.dispatcher.admin.v1.DispatcherAdmin/ListExecutors',
                request_serializer=dispatcher__admin__pb2.ExecutorListRequest.SerializeToString,
                response_deserializer=dispatcher__admin__pb2.ExecutorListResponse.FromString,
                _registered_method=True)


class DispatcherAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExecutors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLoop,
                    request_deserializer=dispatcher__admin__pb2.LoopCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'PauseLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseLoop,
                    request_deserializer=dispatcher__admin__pb2.LoopCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'ResumeLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeLoop,
                    request_deserializer=dispatcher__admin__pb2.LoopCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'StopLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.StopLoop,
                    request_deserializer=dispatcher__admin__pb2.LoopCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'ConfirmLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmLoop,
                    request_deserializer=dispatcher__admin__pb2.ConfirmLoopRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'StopRound': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRound,
                    request_deserializer=dispatcher__admin__pb2.RoundCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'StopStep': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStep,
                    request_deserializer=dispatcher__admin__pb2.StepCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'StopJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StopJob,
                    request_deserializer=dispatcher__admin__pb2.JobCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'StopTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTask,
                    request_deserializer=dispatcher__admin__pb2.TaskCommandRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'TriggerDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerDispatch,
                    request_deserializer=dispatcher__admin__pb2.TriggerDispatchRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.CommandResponse.SerializeToString,
            ),
            'GetRuntimeSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeSummary,
                    request_deserializer=dispatcher__admin__pb2.RuntimeSummaryRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.RuntimeSummaryResponse.SerializeToString,
            ),
            'GetExecutor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutor,
                    request_deserializer=dispatcher__admin__pb2.ExecutorReadRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.ExecutorReadResponse.SerializeToString,
            ),
            'ListExecutors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutors,
                    request_deserializer=dispatcher__admin__pb2.ExecutorListRequest.FromString,
                    response_serializer=dispatcher__admin__pb2.ExecutorListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saki.dispatcher.admin.v1.DispatcherAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saki.dispatcher.admin.v1.DispatcherAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatcherAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StartLoop',
            dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/PauseLoop',
            dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/ResumeLoop',
            dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StopLoop',
            dispatcher__admin__pb2.LoopCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/ConfirmLoop',
            dispatcher__admin__pb2.ConfirmLoopRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StopRound',
            dispatcher__admin__pb2.RoundCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StopStep',
            dispatcher__admin__pb2.StepCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StopJob',
            dispatcher__admin__pb2.JobCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/StopTask',
            dispatcher__admin__pb2.TaskCommandRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/TriggerDispatch',
            dispatcher__admin__pb2.TriggerDispatchRequest.SerializeToString,
            dispatcher__admin__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/GetRuntimeSummary',
            dispatcher__admin__pb2.RuntimeSummaryRequest.SerializeToString,
            dispatcher__admin__pb2.RuntimeSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecutor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/GetExecutor',
            dispatcher__admin__pb2.ExecutorReadRequest.SerializeToString,
            dispatcher__admin__pb2.ExecutorReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExecutors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.dispatcher.admin.v1.DispatcherAdmin/ListExecutors',
            dispatcher__admin__pb2.ExecutorListRequest.SerializeToString,
            dispatcher__admin__pb2.ExecutorListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
