# Generated by manual protobuf builder. DO NOT EDIT!
# source: runtime_agent.proto

from google.protobuf import descriptor_pb2
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()


def _build_file_descriptor() -> descriptor_pb2.FileDescriptorProto:
    file_proto = descriptor_pb2.FileDescriptorProto()
    file_proto.name = "runtime_agent.proto"
    file_proto.package = "saki.runtime.v1"
    file_proto.syntax = "proto3"
    file_proto.dependency.append("google/protobuf/struct.proto")

    # Enums
    job_status = file_proto.enum_type.add()
    job_status.name = "JobStatus"
    job_status.value.add(name="JOB_STATUS_UNSPECIFIED", number=0)
    job_status.value.add(name="CREATED", number=1)
    job_status.value.add(name="QUEUED", number=2)
    job_status.value.add(name="RUNNING", number=3)
    job_status.value.add(name="STOPPING", number=4)
    job_status.value.add(name="STOPPED", number=5)
    job_status.value.add(name="SUCCEEDED", number=6)
    job_status.value.add(name="FAILED", number=7)

    job_type = file_proto.enum_type.add()
    job_type.name = "JobType"
    job_type.value.add(name="JOB_TYPE_UNSPECIFIED", number=0)
    job_type.value.add(name="TRAIN_DETECTION", number=1)
    job_type.value.add(name="SCORE_UNLABELED", number=2)
    job_type.value.add(name="EXPORT_MODEL", number=3)

    error_code = file_proto.enum_type.add()
    error_code.name = "ErrorCode"
    error_code.value.add(name="ERROR_CODE_UNSPECIFIED", number=0)
    error_code.value.add(name="INVALID_ARGUMENT", number=1)
    error_code.value.add(name="NOT_FOUND", number=2)
    error_code.value.add(name="CONFLICT", number=3)
    error_code.value.add(name="UNAUTHORIZED", number=4)
    error_code.value.add(name="FORBIDDEN", number=5)
    error_code.value.add(name="UNAVAILABLE", number=6)
    error_code.value.add(name="INTERNAL", number=7)

    ack_status = file_proto.enum_type.add()
    ack_status.name = "AckStatus"
    ack_status.value.add(name="ACK_STATUS_UNSPECIFIED", number=0)
    ack_status.value.add(name="ACK_OK", number=1)
    ack_status.value.add(name="ACK_ERROR", number=2)

    # Messages
    resources = file_proto.message_type.add()
    resources.name = "Resources"
    field = resources.field.add()
    field.name = "gpu_count"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = resources.field.add()
    field.name = "gpu_device_ids"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = resources.field.add()
    field.name = "cpu_workers"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = resources.field.add()
    field.name = "memory_mb"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32

    plugin_info = file_proto.message_type.add()
    plugin_info.name = "PluginInfo"
    field = plugin_info.field.add()
    field.name = "id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = plugin_info.field.add()
    field.name = "version"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = plugin_info.field.add()
    field.name = "capabilities"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    register = file_proto.message_type.add()
    register.name = "Register"
    field = register.field.add()
    field.name = "agent_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = register.field.add()
    field.name = "version"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = register.field.add()
    field.name = "plugins"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.PluginInfo"
    field = register.field.add()
    field.name = "resources"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Resources"

    heartbeat = file_proto.message_type.add()
    heartbeat.name = "Heartbeat"
    field = heartbeat.field.add()
    field.name = "agent_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = heartbeat.field.add()
    field.name = "ts"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT64
    field = heartbeat.field.add()
    field.name = "resources"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Resources"

    model_ref = file_proto.message_type.add()
    model_ref.name = "ModelRef"
    field = model_ref.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = model_ref.field.add()
    field.name = "artifact_name"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    create_job = file_proto.message_type.add()
    create_job.name = "CreateJob"
    field = create_job.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = create_job.field.add()
    field.name = "job_type"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.JobType"
    field = create_job.field.add()
    field.name = "project_id"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = create_job.field.add()
    field.name = "source_commit_id"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = create_job.field.add()
    field.name = "plugin_id"
    field.number = 5
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = create_job.field.add()
    field.name = "params"
    field.number = 6
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"
    field = create_job.field.add()
    field.name = "resources"
    field.number = 7
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Resources"

    start_job = file_proto.message_type.add()
    start_job.name = "StartJob"
    field = start_job.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    stop_job = file_proto.message_type.add()
    stop_job.name = "StopJob"
    field = stop_job.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    query_samples = file_proto.message_type.add()
    query_samples.name = "QuerySamples"
    field = query_samples.field.add()
    field.name = "project_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_samples.field.add()
    field.name = "source_commit_id"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_samples.field.add()
    field.name = "plugin_id"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_samples.field.add()
    field.name = "model_ref"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.ModelRef"
    field = query_samples.field.add()
    field.name = "unit"
    field.number = 5
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_samples.field.add()
    field.name = "strategy"
    field.number = 6
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_samples.field.add()
    field.name = "topk"
    field.number = 7
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = query_samples.field.add()
    field.name = "params"
    field.number = 8
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"

    command = file_proto.message_type.add()
    command.name = "Command"
    command.oneof_decl.add(name="payload")
    field = command.field.add()
    field.name = "request_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = command.field.add()
    field.name = "create_job"
    field.number = 10
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.CreateJob"
    field.oneof_index = 0
    field = command.field.add()
    field.name = "start_job"
    field.number = 11
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.StartJob"
    field.oneof_index = 0
    field = command.field.add()
    field.name = "stop_job"
    field.number = 12
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.StopJob"
    field.oneof_index = 0
    field = command.field.add()
    field.name = "query_samples"
    field.number = 13
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.QuerySamples"
    field.oneof_index = 0

    job_created = file_proto.message_type.add()
    job_created.name = "JobCreated"
    field = job_created.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = job_created.field.add()
    field.name = "status"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.JobStatus"

    job_status_result = file_proto.message_type.add()
    job_status_result.name = "JobStatusResult"
    field = job_status_result.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = job_status_result.field.add()
    field.name = "status"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.JobStatus"

    query_candidate = file_proto.message_type.add()
    query_candidate.name = "QueryCandidate"
    field = query_candidate.field.add()
    field.name = "sample_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_candidate.field.add()
    field.name = "score"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE
    field = query_candidate.field.add()
    field.name = "reason"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"

    query_result = file_proto.message_type.add()
    query_result.name = "QueryResult"
    field = query_result.field.add()
    field.name = "model_job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = query_result.field.add()
    field.name = "candidates"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.QueryCandidate"

    result = file_proto.message_type.add()
    result.name = "Result"
    result.oneof_decl.add(name="payload")
    field = result.field.add()
    field.name = "request_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = result.field.add()
    field.name = "job_created"
    field.number = 10
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.JobCreated"
    field.oneof_index = 0
    field = result.field.add()
    field.name = "job_status"
    field.number = 11
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.JobStatusResult"
    field.oneof_index = 0
    field = result.field.add()
    field.name = "query_result"
    field.number = 12
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.QueryResult"
    field.oneof_index = 0

    log_event = file_proto.message_type.add()
    log_event.name = "LogEvent"
    field = log_event.field.add()
    field.name = "level"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = log_event.field.add()
    field.name = "message"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = log_event.field.add()
    field.name = "logger"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    progress_event = file_proto.message_type.add()
    progress_event.name = "ProgressEvent"
    field = progress_event.field.add()
    field.name = "epoch"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = progress_event.field.add()
    field.name = "step"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = progress_event.field.add()
    field.name = "total_steps"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = progress_event.field.add()
    field.name = "eta_sec"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32

    metric_event = file_proto.message_type.add()
    metric_event.name = "MetricEvent"
    field = metric_event.field.add()
    field.name = "step"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = metric_event.field.add()
    field.name = "epoch"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    field = metric_event.field.add()
    field.name = "metrics"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"

    artifact_event = file_proto.message_type.add()
    artifact_event.name = "ArtifactEvent"
    field = artifact_event.field.add()
    field.name = "kind"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = artifact_event.field.add()
    field.name = "name"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = artifact_event.field.add()
    field.name = "uri"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = artifact_event.field.add()
    field.name = "meta"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"

    status_event = file_proto.message_type.add()
    status_event.name = "StatusEvent"
    field = status_event.field.add()
    field.name = "status"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.JobStatus"
    field = status_event.field.add()
    field.name = "reason"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    event = file_proto.message_type.add()
    event.name = "Event"
    event.oneof_decl.add(name="payload")
    field = event.field.add()
    field.name = "job_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = event.field.add()
    field.name = "seq"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT64
    field = event.field.add()
    field.name = "ts"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_INT64
    field = event.field.add()
    field.name = "log"
    field.number = 10
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.LogEvent"
    field.oneof_index = 0
    field = event.field.add()
    field.name = "progress"
    field.number = 11
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.ProgressEvent"
    field.oneof_index = 0
    field = event.field.add()
    field.name = "metric"
    field.number = 12
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.MetricEvent"
    field.oneof_index = 0
    field = event.field.add()
    field.name = "artifact"
    field.number = 13
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.ArtifactEvent"
    field.oneof_index = 0
    field = event.field.add()
    field.name = "status"
    field.number = 14
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.StatusEvent"
    field.oneof_index = 0

    error = file_proto.message_type.add()
    error.name = "Error"
    field = error.field.add()
    field.name = "request_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = error.field.add()
    field.name = "code"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.ErrorCode"
    field = error.field.add()
    field.name = "message"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = error.field.add()
    field.name = "details"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".google.protobuf.Struct"

    ack = file_proto.message_type.add()
    ack.name = "Ack"
    field = ack.field.add()
    field.name = "request_id"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    field = ack.field.add()
    field.name = "status"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
    field.type_name = ".saki.runtime.v1.AckStatus"
    field = ack.field.add()
    field.name = "message"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_STRING

    agent_message = file_proto.message_type.add()
    agent_message.name = "AgentMessage"
    agent_message.oneof_decl.add(name="payload")
    field = agent_message.field.add()
    field.name = "register"
    field.number = 1
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Register"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "heartbeat"
    field.number = 2
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Heartbeat"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "command"
    field.number = 3
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Command"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "event"
    field.number = 4
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Event"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "result"
    field.number = 5
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Result"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "error"
    field.number = 6
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Error"
    field.oneof_index = 0
    field = agent_message.field.add()
    field.name = "ack"
    field.number = 7
    field.label = descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    field.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
    field.type_name = ".saki.runtime.v1.Ack"
    field.oneof_index = 0

    # Service
    service = file_proto.service.add()
    service.name = "RuntimeAgent"
    method = service.method.add()
    method.name = "Stream"
    method.input_type = ".saki.runtime.v1.AgentMessage"
    method.output_type = ".saki.runtime.v1.AgentMessage"
    method.client_streaming = True
    method.server_streaming = True

    return file_proto


_POOL = _descriptor_pool.Default()
try:
    DESCRIPTOR = _POOL.Add(_build_file_descriptor())
except Exception:
    DESCRIPTOR = _POOL.FindFileByName("runtime_agent.proto")

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "runtime_agent_pb2", globals())
