# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_domain_pb2 as runtime__domain__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_domain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeDomainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBranchHead = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/GetBranchHead',
                request_serializer=runtime__domain__pb2.GetBranchHeadRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.GetBranchHeadResponse.FromString,
                _registered_method=True)
        self.CountNewLabelsSinceCommit = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/CountNewLabelsSinceCommit',
                request_serializer=runtime__domain__pb2.CountNewLabelsSinceCommitRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.CountNewLabelsSinceCommitResponse.FromString,
                _registered_method=True)
        self.CreateSimulationCommitFromOracle = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/CreateSimulationCommitFromOracle',
                request_serializer=runtime__domain__pb2.CreateSimulationCommitFromOracleRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.CreateSimulationCommitFromOracleResponse.FromString,
                _registered_method=True)
        self.AdvanceBranchHead = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/AdvanceBranchHead',
                request_serializer=runtime__domain__pb2.AdvanceBranchHeadRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.AdvanceBranchHeadResponse.FromString,
                _registered_method=True)
        self.QueryData = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/QueryData',
                request_serializer=runtime__domain__pb2.DataRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.DataResponse.FromString,
                _registered_method=True)
        self.CreateUploadTicket = channel.unary_unary(
                '/saki.runtime.domain.v1.RuntimeDomain/CreateUploadTicket',
                request_serializer=runtime__domain__pb2.UploadTicketRequest.SerializeToString,
                response_deserializer=runtime__domain__pb2.UploadTicketResponse.FromString,
                _registered_method=True)


class RuntimeDomainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBranchHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountNewLabelsSinceCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSimulationCommitFromOracle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceBranchHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUploadTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeDomainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBranchHead': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBranchHead,
                    request_deserializer=runtime__domain__pb2.GetBranchHeadRequest.FromString,
                    response_serializer=runtime__domain__pb2.GetBranchHeadResponse.SerializeToString,
            ),
            'CountNewLabelsSinceCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.CountNewLabelsSinceCommit,
                    request_deserializer=runtime__domain__pb2.CountNewLabelsSinceCommitRequest.FromString,
                    response_serializer=runtime__domain__pb2.CountNewLabelsSinceCommitResponse.SerializeToString,
            ),
            'CreateSimulationCommitFromOracle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSimulationCommitFromOracle,
                    request_deserializer=runtime__domain__pb2.CreateSimulationCommitFromOracleRequest.FromString,
                    response_serializer=runtime__domain__pb2.CreateSimulationCommitFromOracleResponse.SerializeToString,
            ),
            'AdvanceBranchHead': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceBranchHead,
                    request_deserializer=runtime__domain__pb2.AdvanceBranchHeadRequest.FromString,
                    response_serializer=runtime__domain__pb2.AdvanceBranchHeadResponse.SerializeToString,
            ),
            'QueryData': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryData,
                    request_deserializer=runtime__domain__pb2.DataRequest.FromString,
                    response_serializer=runtime__domain__pb2.DataResponse.SerializeToString,
            ),
            'CreateUploadTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUploadTicket,
                    request_deserializer=runtime__domain__pb2.UploadTicketRequest.FromString,
                    response_serializer=runtime__domain__pb2.UploadTicketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saki.runtime.domain.v1.RuntimeDomain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saki.runtime.domain.v1.RuntimeDomain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeDomain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBranchHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/GetBranchHead',
            runtime__domain__pb2.GetBranchHeadRequest.SerializeToString,
            runtime__domain__pb2.GetBranchHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountNewLabelsSinceCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/CountNewLabelsSinceCommit',
            runtime__domain__pb2.CountNewLabelsSinceCommitRequest.SerializeToString,
            runtime__domain__pb2.CountNewLabelsSinceCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSimulationCommitFromOracle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/CreateSimulationCommitFromOracle',
            runtime__domain__pb2.CreateSimulationCommitFromOracleRequest.SerializeToString,
            runtime__domain__pb2.CreateSimulationCommitFromOracleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceBranchHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/AdvanceBranchHead',
            runtime__domain__pb2.AdvanceBranchHeadRequest.SerializeToString,
            runtime__domain__pb2.AdvanceBranchHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/QueryData',
            runtime__domain__pb2.DataRequest.SerializeToString,
            runtime__domain__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUploadTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saki.runtime.domain.v1.RuntimeDomain/CreateUploadTicket',
            runtime__domain__pb2.UploadTicketRequest.SerializeToString,
            runtime__domain__pb2.UploadTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
