# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# source: runtime_agent.proto

import grpc

from . import runtime_agent_pb2 as runtime__agent__pb2


class RuntimeAgentStub(object):
    def __init__(self, channel):
        self.Stream = channel.stream_stream(
            "/saki.runtime.v1.RuntimeAgent/Stream",
            request_serializer=runtime__agent__pb2.AgentMessage.SerializeToString,
            response_deserializer=runtime__agent__pb2.AgentMessage.FromString,
        )


class RuntimeAgentServicer(object):
    async def Stream(self, request_iterator, context):
        raise NotImplementedError("Method not implemented!")


def add_RuntimeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Stream": grpc.aio.stream_stream_rpc_method_handler(
            servicer.Stream,
            request_deserializer=runtime__agent__pb2.AgentMessage.FromString,
            response_serializer=runtime__agent__pb2.AgentMessage.SerializeToString,
        )
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "saki.runtime.v1.RuntimeAgent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))

