"""init_schema

Revision ID: edef87f62bca
Revises: 
Create Date: 2026-03-07 02:09:49.284534

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edef87f62bca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('storage_type', sa.Enum('LOCAL', 'S3', name='storagetype'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=31), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_hash'), 'asset', ['hash'], unique=True)
    op.create_table('import_task',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_task_finished_at'), 'import_task', ['finished_at'], unique=False)
    op.create_index(op.f('ix_import_task_mode'), 'import_task', ['mode'], unique=False)
    op.create_index(op.f('ix_import_task_resource_id'), 'import_task', ['resource_id'], unique=False)
    op.create_index(op.f('ix_import_task_resource_type'), 'import_task', ['resource_type'], unique=False)
    op.create_index(op.f('ix_import_task_started_at'), 'import_task', ['started_at'], unique=False)
    op.create_index(op.f('ix_import_task_status'), 'import_task', ['status'], unique=False)
    op.create_index(op.f('ix_import_task_user_id'), 'import_task', ['user_id'], unique=False)
    op.create_table('loop',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mode', sa.Enum('ACTIVE_LEARNING', 'SIMULATION', 'MANUAL', name='loopmode'), nullable=False),
    sa.Column('phase', sa.Enum('AL_BOOTSTRAP', 'AL_TRAIN', 'AL_EVAL', 'AL_SCORE', 'AL_SELECT', 'AL_WAIT_USER', 'AL_FINALIZE', 'SIM_BOOTSTRAP', 'SIM_TRAIN', 'SIM_EVAL', 'SIM_SCORE', 'SIM_SELECT', 'SIM_WAIT_USER', 'SIM_FINALIZE', 'MANUAL_BOOTSTRAP', 'MANUAL_TRAIN', 'MANUAL_EVAL', 'MANUAL_FINALIZE', name='loopphase'), nullable=False),
    sa.Column('model_arch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('lifecycle', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'STOPPING', 'STOPPED', 'COMPLETED', 'FAILED', name='looplifecycle'), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('query_batch_size', sa.Integer(), nullable=False),
    sa.Column('min_new_labels_per_round', sa.Integer(), nullable=False),
    sa.Column('active_snapshot_version_id', sa.Uuid(), nullable=True),
    sa.Column('last_confirmed_commit_id', sa.Uuid(), nullable=True),
    sa.Column('terminal_reason', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', name='uq_loop_branch_id')
    )
    op.create_index(op.f('ix_loop_active_snapshot_version_id'), 'loop', ['active_snapshot_version_id'], unique=False)
    op.create_index(op.f('ix_loop_branch_id'), 'loop', ['branch_id'], unique=False)
    op.create_index(op.f('ix_loop_last_confirmed_commit_id'), 'loop', ['last_confirmed_commit_id'], unique=False)
    op.create_index(op.f('ix_loop_lifecycle'), 'loop', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_loop_mode'), 'loop', ['mode'], unique=False)
    op.create_index(op.f('ix_loop_phase'), 'loop', ['phase'], unique=False)
    op.create_index(op.f('ix_loop_project_id'), 'loop', ['project_id'], unique=False)
    op.create_table('loop_snapshot_version',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loop_id', sa.Uuid(), nullable=False),
    sa.Column('version_index', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('update_mode', sa.Enum('INIT', 'APPEND_ALL_TO_POOL', 'APPEND_SPLIT', name='snapshotupdatemode'), nullable=False),
    sa.Column('val_policy', sa.Enum('ANCHOR_ONLY', 'EXPAND_WITH_BATCH_VAL', name='snapshotvalpolicy'), nullable=False),
    sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('rule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('manifest_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loop_id', 'version_index', name='uq_loop_snapshot_version_loop_version')
    )
    op.create_index(op.f('ix_loop_snapshot_version_created_by'), 'loop_snapshot_version', ['created_by'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_loop_id'), 'loop_snapshot_version', ['loop_id'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_manifest_hash'), 'loop_snapshot_version', ['manifest_hash'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_parent_version_id'), 'loop_snapshot_version', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_update_mode'), 'loop_snapshot_version', ['update_mode'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_val_policy'), 'loop_snapshot_version', ['val_policy'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_version_version_index'), 'loop_snapshot_version', ['version_index'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_type', sa.Enum('CLASSIFICATION', 'DETECTION', 'SEGMENTATION', name='tasktype'), nullable=False),
    sa.Column('dataset_type', sa.Enum('CLASSIC', 'FEDO', name='datasettype'), nullable=False),
    sa.Column('enabled_annotation_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'RESOURCE', name='roletype'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_supremo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('runtime_command_log',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_command_log_command_id'), 'runtime_command_log', ['command_id'], unique=True)
    op.create_index(op.f('ix_runtime_command_log_status'), 'runtime_command_log', ['status'], unique=False)
    op.create_table('runtime_executor',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('executor_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('current_task_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('plugin_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_executor_current_task_id'), 'runtime_executor', ['current_task_id'], unique=False)
    op.create_index(op.f('ix_runtime_executor_executor_id'), 'runtime_executor', ['executor_id'], unique=True)
    op.create_index(op.f('ix_runtime_executor_is_online'), 'runtime_executor', ['is_online'], unique=False)
    op.create_index(op.f('ix_runtime_executor_last_seen_at'), 'runtime_executor', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_runtime_executor_status'), 'runtime_executor', ['status'], unique=False)
    op.create_table('runtime_executor_stats',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.Column('busy_count', sa.Integer(), nullable=False),
    sa.Column('available_count', sa.Integer(), nullable=False),
    sa.Column('availability_rate', sa.Float(), nullable=False),
    sa.Column('pending_assign_count', sa.Integer(), nullable=False),
    sa.Column('pending_stop_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_executor_stats_ts'), 'runtime_executor_stats', ['ts'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('ROLE_CREATE', 'ROLE_UPDATE', 'ROLE_DELETE', 'USER_ROLE_ASSIGN', 'USER_ROLE_REVOKE', 'MEMBER_ADD', 'MEMBER_UPDATE', 'MEMBER_REMOVE', 'PERMISSION_DENIED', 'PERMISSION_GRANTED', name='auditaction'), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_by'), 'audit_log', ['created_by'], unique=False)
    op.create_index(op.f('ix_audit_log_updated_by'), 'audit_log', ['updated_by'], unique=False)
    op.create_table('commit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author_type', sa.Enum('USER', 'MODEL', 'SYSTEM', name='authortype'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_author_type'), 'commit', ['author_type'], unique=False)
    op.create_index(op.f('ix_commit_commit_hash'), 'commit', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_commit_parent_id'), 'commit', ['parent_id'], unique=False)
    op.create_index(op.f('ix_commit_project_id'), 'commit', ['project_id'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('type', sa.Enum('CLASSIC', 'FEDO', name='datasettype'), nullable=False),
    sa.Column('allow_duplicate_sample_names', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_owner_id'), 'dataset', ['owner_id'], unique=False)
    op.create_table('import_task_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('event_subtype', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['import_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'seq', name='uq_import_task_event_task_seq')
    )
    op.create_index(op.f('ix_import_task_event_event_type'), 'import_task_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_import_task_event_seq'), 'import_task_event', ['seq'], unique=False)
    op.create_index(op.f('ix_import_task_event_task_id'), 'import_task_event', ['task_id'], unique=False)
    op.create_index(op.f('ix_import_task_event_ts'), 'import_task_event', ['ts'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('shortcut', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('sort_order > 0', name='ck_label_sort_order_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_label_name'),
    sa.UniqueConstraint('project_id', 'sort_order', name='uq_project_label_sort_order')
    )
    op.create_index(op.f('ix_label_project_id'), 'label', ['project_id'], unique=False)
    op.create_table('resource_member',
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('DATASET', 'PROJECT', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'user_id', name='uq_resource_member')
    )
    op.create_index(op.f('ix_resource_member_created_by'), 'resource_member', ['created_by'], unique=False)
    op.create_index(op.f('ix_resource_member_resource_id'), 'resource_member', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_member_resource_type'), 'resource_member', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resource_member_updated_by'), 'resource_member', ['updated_by'], unique=False)
    op.create_index(op.f('ix_resource_member_user_id'), 'resource_member', ['user_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('system_setting',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_setting_updated_by'), 'system_setting', ['updated_by'], unique=False)
    op.create_table('user_system_role',
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_system_role_created_by'), 'user_system_role', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_system_role_role_id'), 'user_system_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_system_role_updated_by'), 'user_system_role', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_system_role_user_id'), 'user_system_role', ['user_id'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('head_commit_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['head_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_branch_name')
    )
    op.create_index(op.f('ix_branch_name'), 'branch', ['name'], unique=False)
    op.create_index(op.f('ix_branch_project_id'), 'branch', ['project_id'], unique=False)
    op.create_table('project_dataset',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id')
    )
    op.create_table('round',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('loop_id', sa.Uuid(), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('ACTIVE_LEARNING', 'SIMULATION', 'MANUAL', name='loopmode'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED', name='roundstatus'), nullable=False),
    sa.Column('step_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('input_commit_id', sa.Uuid(), nullable=True),
    sa.Column('retry_of_round_id', sa.Uuid(), nullable=True),
    sa.Column('retry_reason', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('assigned_executor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_reason', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_revealed_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_selected_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_effective_min_required', sa.Integer(), nullable=False),
    sa.Column('final_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('final_artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loop_id', 'round_index', 'attempt_index', name='uq_round_loop_round_attempt')
    )
    op.create_index(op.f('ix_round_assigned_executor_id'), 'round', ['assigned_executor_id'], unique=False)
    op.create_index(op.f('ix_round_attempt_index'), 'round', ['attempt_index'], unique=False)
    op.create_index(op.f('ix_round_confirmed_at'), 'round', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_round_loop_id'), 'round', ['loop_id'], unique=False)
    op.create_index(op.f('ix_round_plugin_id'), 'round', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_round_project_id'), 'round', ['project_id'], unique=False)
    op.create_index(op.f('ix_round_round_index'), 'round', ['round_index'], unique=False)
    op.create_index(op.f('ix_round_state'), 'round', ['state'], unique=False)
    op.create_table('sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_group', sa.JSON(), nullable=True),
    sa.Column('primary_asset_id', sa.Uuid(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_dataset_id'), 'sample', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_sample_name'), 'sample', ['name'], unique=False)
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('STEP', 'PREDICTION', name='runtimetaskkind'), nullable=False),
    sa.Column('task_type', sa.Enum('TRAIN', 'EVAL', 'SCORE', 'SELECT', 'PREDICT', 'CUSTOM', name='runtimetasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'DISPATCHING', 'SYNCING_ENV', 'PROBING_RUNTIME', 'BINDING_DEVICE', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED', name='runtimetaskstatus'), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('depends_on_task_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('input_commit_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('assigned_executor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['input_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assigned_executor_id'), 'task', ['assigned_executor_id'], unique=False)
    op.create_index(op.f('ix_task_input_commit_id'), 'task', ['input_commit_id'], unique=False)
    op.create_index(op.f('ix_task_kind'), 'task', ['kind'], unique=False)
    op.create_index(op.f('ix_task_plugin_id'), 'task', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task_type'), 'task', ['task_type'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('lineage_id', sa.Uuid(), nullable=False),
    sa.Column('view_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('RECT', 'OBB', 'POLYGON', 'POLYLINE', 'POINT', 'KEYPOINTS', name='annotationtype'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'MODEL', 'SYSTEM', 'IMPORTED', 'CONFIRMED_MODEL', name='annotationsource'), nullable=False),
    sa.Column('geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('annotator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_confidence'), 'annotation', ['confidence'], unique=False)
    op.create_index(op.f('ix_annotation_group_id'), 'annotation', ['group_id'], unique=False)
    op.create_index(op.f('ix_annotation_label_id'), 'annotation', ['label_id'], unique=False)
    op.create_index(op.f('ix_annotation_lineage_id'), 'annotation', ['lineage_id'], unique=False)
    op.create_index(op.f('ix_annotation_parent_id'), 'annotation', ['parent_id'], unique=False)
    op.create_index(op.f('ix_annotation_project_id'), 'annotation', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotation_sample_id'), 'annotation', ['sample_id'], unique=False)
    op.create_index(op.f('ix_annotation_source'), 'annotation', ['source'], unique=False)
    op.create_index(op.f('ix_annotation_type'), 'annotation', ['type'], unique=False)
    op.create_table('annotation_draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sample_id', 'user_id', 'branch_name', name='uq_annotation_draft')
    )
    op.create_index(op.f('ix_annotation_draft_branch_name'), 'annotation_draft', ['branch_name'], unique=False)
    op.create_index(op.f('ix_annotation_draft_project_id'), 'annotation_draft', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotation_draft_sample_id'), 'annotation_draft', ['sample_id'], unique=False)
    op.create_index(op.f('ix_annotation_draft_user_id'), 'annotation_draft', ['user_id'], unique=False)
    op.create_table('commit_sample_state',
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('LABELED', 'EMPTY_CONFIRMED', name='commitsamplereviewstate'), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('commit_id', 'sample_id')
    )
    op.create_index('idx_commit_sample_state_lookup', 'commit_sample_state', ['commit_id', 'sample_id', 'state'], unique=False)
    op.create_index(op.f('ix_commit_sample_state_commit_id'), 'commit_sample_state', ['commit_id'], unique=False)
    op.create_index(op.f('ix_commit_sample_state_project_id'), 'commit_sample_state', ['project_id'], unique=False)
    op.create_index(op.f('ix_commit_sample_state_sample_id'), 'commit_sample_state', ['sample_id'], unique=False)
    op.create_index(op.f('ix_commit_sample_state_state'), 'commit_sample_state', ['state'], unique=False)
    op.create_table('loop_sample_state',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loop_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('visible_in_train', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('SNAPSHOT_INIT', 'SEED_INIT', 'ROUND_REVEAL', 'FORCE_REVEAL', name='visibilitysource'), nullable=False),
    sa.Column('revealed_round_index', sa.Integer(), nullable=True),
    sa.Column('reveal_commit_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['loop_id'], ['loop.id'], ),
    sa.ForeignKeyConstraint(['reveal_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('loop_id', 'sample_id')
    )
    op.create_index(op.f('ix_loop_sample_state_reveal_commit_id'), 'loop_sample_state', ['reveal_commit_id'], unique=False)
    op.create_index(op.f('ix_loop_sample_state_revealed_round_index'), 'loop_sample_state', ['revealed_round_index'], unique=False)
    op.create_index(op.f('ix_loop_sample_state_source'), 'loop_sample_state', ['source'], unique=False)
    op.create_index(op.f('ix_loop_sample_state_visible_in_train'), 'loop_sample_state', ['visible_in_train'], unique=False)
    op.create_table('loop_snapshot_sample',
    sa.Column('snapshot_version_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('partition', sa.Enum('TRAIN_SEED', 'TRAIN_POOL', 'VAL_ANCHOR', 'VAL_BATCH', 'TEST_ANCHOR', 'TEST_BATCH', name='snapshotpartition'), nullable=False),
    sa.Column('cohort_index', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['snapshot_version_id'], ['loop_snapshot_version.id'], ),
    sa.PrimaryKeyConstraint('snapshot_version_id', 'sample_id')
    )
    op.create_index(op.f('ix_loop_snapshot_sample_cohort_index'), 'loop_snapshot_sample', ['cohort_index'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_sample_locked'), 'loop_snapshot_sample', ['locked'], unique=False)
    op.create_index(op.f('ix_loop_snapshot_sample_partition'), 'loop_snapshot_sample', ['partition'], unique=False)
    op.create_table('model',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_commit_id', sa.Uuid(), nullable=True),
    sa.Column('source_round_id', sa.Uuid(), nullable=True),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('parent_model_id', sa.Uuid(), nullable=True),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_arch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_artifact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weights_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('publish_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_model_arch'), 'model', ['model_arch'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_index(op.f('ix_model_parent_model_id'), 'model', ['parent_model_id'], unique=False)
    op.create_index(op.f('ix_model_plugin_id'), 'model', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_model_project_id'), 'model', ['project_id'], unique=False)
    op.create_index(op.f('ix_model_source_commit_id'), 'model', ['source_commit_id'], unique=False)
    op.create_index(op.f('ix_model_source_round_id'), 'model', ['source_round_id'], unique=False)
    op.create_index(op.f('ix_model_source_task_id'), 'model', ['source_task_id'], unique=False)
    op.create_table('round_selection_override',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('op', sa.Enum('INCLUDE', 'EXCLUDE', name='roundselectionoverrideop'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'sample_id', name='uq_round_selection_override_round_sample')
    )
    op.create_index(op.f('ix_round_selection_override_created_by'), 'round_selection_override', ['created_by'], unique=False)
    op.create_index(op.f('ix_round_selection_override_op'), 'round_selection_override', ['op'], unique=False)
    op.create_index(op.f('ix_round_selection_override_round_id'), 'round_selection_override', ['round_id'], unique=False)
    op.create_index(op.f('ix_round_selection_override_sample_id'), 'round_selection_override', ['sample_id'], unique=False)
    op.create_table('step',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('step_type', sa.Enum('TRAIN', 'EVAL', 'SCORE', 'SELECT', 'CUSTOM', name='steptype'), nullable=False),
    sa.Column('dispatch_kind', sa.Enum('DISPATCHABLE', 'ORCHESTRATOR', name='stepdispatchkind'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'READY', 'DISPATCHING', 'SYNCING_ENV', 'PROBING_RUNTIME', 'BINDING_DEVICE', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('depends_on_step_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resolved_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('input_commit_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_executor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['input_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'step_index', name='uq_step_order')
    )
    op.create_index(op.f('ix_step_assigned_executor_id'), 'step', ['assigned_executor_id'], unique=False)
    op.create_index(op.f('ix_step_dispatch_kind'), 'step', ['dispatch_kind'], unique=False)
    op.create_index(op.f('ix_step_input_commit_id'), 'step', ['input_commit_id'], unique=False)
    op.create_index(op.f('ix_step_round_id'), 'step', ['round_id'], unique=False)
    op.create_index(op.f('ix_step_round_index'), 'step', ['round_index'], unique=False)
    op.create_index(op.f('ix_step_state'), 'step', ['state'], unique=False)
    op.create_index(op.f('ix_step_step_index'), 'step', ['step_index'], unique=False)
    op.create_index(op.f('ix_step_step_type'), 'step', ['step_type'], unique=False)
    op.create_index(op.f('ix_step_task_id'), 'step', ['task_id'], unique=True)
    op.create_table('task_candidate_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prediction_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'sample_id', name='uq_task_candidate_item')
    )
    op.create_index(op.f('ix_task_candidate_item_sample_id'), 'task_candidate_item', ['sample_id'], unique=False)
    op.create_index(op.f('ix_task_candidate_item_task_id'), 'task_candidate_item', ['task_id'], unique=False)
    op.create_table('task_dispatch_outbox',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('executor_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dispatch_outbox_request_id'), 'task_dispatch_outbox', ['request_id'], unique=True)
    op.create_index('ix_task_dispatch_outbox_status_next_attempt_at', 'task_dispatch_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_task_dispatch_outbox_task_id'), 'task_dispatch_outbox', ['task_id'], unique=False)
    op.create_table('task_event',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'seq', name='uq_task_event_seq')
    )
    op.create_index(op.f('ix_task_event_event_type'), 'task_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_event_seq'), 'task_event', ['seq'], unique=False)
    op.create_index(op.f('ix_task_event_task_id'), 'task_event', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_event_ts'), 'task_event', ['ts'], unique=False)
    op.create_table('task_metric_point',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_metric_point_epoch'), 'task_metric_point', ['epoch'], unique=False)
    op.create_index(op.f('ix_task_metric_point_metric_name'), 'task_metric_point', ['metric_name'], unique=False)
    op.create_index(op.f('ix_task_metric_point_step'), 'task_metric_point', ['step'], unique=False)
    op.create_index(op.f('ix_task_metric_point_task_id'), 'task_metric_point', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_metric_point_ts'), 'task_metric_point', ['ts'], unique=False)
    op.create_table('commit_annotation_map',
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('commit_id', 'sample_id', 'annotation_id')
    )
    op.create_index('idx_commit_sample_lookup', 'commit_annotation_map', ['commit_id', 'sample_id', 'annotation_id'], unique=False)
    op.create_index(op.f('ix_commit_annotation_map_annotation_id'), 'commit_annotation_map', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_commit_annotation_map_commit_id'), 'commit_annotation_map', ['commit_id'], unique=False)
    op.create_index(op.f('ix_commit_annotation_map_project_id'), 'commit_annotation_map', ['project_id'], unique=False)
    op.create_index(op.f('ix_commit_annotation_map_sample_id'), 'commit_annotation_map', ['sample_id'], unique=False)
    op.create_table('model_class_schema',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('class_index', sa.Integer(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('class_name_norm', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('schema_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'class_index', name='uq_model_class_schema_model_index'),
    sa.UniqueConstraint('model_id', 'class_name_norm', name='uq_model_class_schema_model_name_norm')
    )
    op.create_index(op.f('ix_model_class_schema_class_index'), 'model_class_schema', ['class_index'], unique=False)
    op.create_index(op.f('ix_model_class_schema_label_id'), 'model_class_schema', ['label_id'], unique=False)
    op.create_index(op.f('ix_model_class_schema_model_id'), 'model_class_schema', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_class_schema_schema_hash'), 'model_class_schema', ['schema_hash'], unique=False)
    op.create_table('prediction',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('base_commit_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('scope_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['base_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_base_commit_id'), 'prediction', ['base_commit_id'], unique=False)
    op.create_index(op.f('ix_prediction_created_by'), 'prediction', ['created_by'], unique=False)
    op.create_index(op.f('ix_prediction_model_id'), 'prediction', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_plugin_id'), 'prediction', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_prediction_project_id'), 'prediction', ['project_id'], unique=False)
    op.create_index(op.f('ix_prediction_scope_type'), 'prediction', ['scope_type'], unique=False)
    op.create_index(op.f('ix_prediction_status'), 'prediction', ['status'], unique=False)
    op.create_index(op.f('ix_prediction_task_id'), 'prediction', ['task_id'], unique=True)
    op.create_table('prediction_binding',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('schema_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('by_index_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('by_name_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_binding_model_id'), 'prediction_binding', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_binding_prediction_id'), 'prediction_binding', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_prediction_binding_schema_hash'), 'prediction_binding', ['schema_hash'], unique=False)
    op.create_table('prediction_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=True),
    sa.Column('geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('prediction_id', 'sample_id')
    )
    op.create_index(op.f('ix_prediction_item_label_id'), 'prediction_item', ['label_id'], unique=False)
    op.create_index(op.f('ix_prediction_item_rank'), 'prediction_item', ['rank'], unique=False)
    op.create_foreign_key('fk_loop_project_id_project', 'loop', 'project', ['project_id'], ['id'])
    op.create_foreign_key('fk_loop_last_confirmed_commit_id_commit', 'loop', 'commit', ['last_confirmed_commit_id'], ['id'])
    op.create_foreign_key('fk_loop_branch_id_branch', 'loop', 'branch', ['branch_id'], ['id'])
    op.create_foreign_key('fk_loop_active_snapshot_version_id_loop_snapshot_version', 'loop', 'loop_snapshot_version', ['active_snapshot_version_id'], ['id'])
    op.create_foreign_key('fk_loop_snapshot_version_24991dae', 'loop_snapshot_version', 'loop_snapshot_version', ['parent_version_id'], ['id'])
    op.create_foreign_key('fk_loop_snapshot_version_created_by_user', 'loop_snapshot_version', 'user', ['created_by'], ['id'])
    op.create_foreign_key('fk_loop_snapshot_version_loop_id_loop', 'loop_snapshot_version', 'loop', ['loop_id'], ['id'])
    op.create_foreign_key('fk_round_project_id_project', 'round', 'project', ['project_id'], ['id'])
    op.create_foreign_key('fk_round_retry_of_round_id_round', 'round', 'round', ['retry_of_round_id'], ['id'])
    op.create_foreign_key('fk_round_loop_id_loop', 'round', 'loop', ['loop_id'], ['id'])
    op.create_foreign_key('fk_round_input_commit_id_commit', 'round', 'commit', ['input_commit_id'], ['id'])
    op.create_foreign_key('fk_model_parent_model_id_model', 'model', 'model', ['parent_model_id'], ['id'])
    op.create_foreign_key('fk_model_source_round_id_round', 'model', 'round', ['source_round_id'], ['id'])
    op.create_foreign_key('fk_model_project_id_project', 'model', 'project', ['project_id'], ['id'])
    op.create_foreign_key('fk_model_created_by_user', 'model', 'user', ['created_by'], ['id'])
    op.create_foreign_key('fk_model_source_task_id_task', 'model', 'task', ['source_task_id'], ['id'])
    op.create_foreign_key('fk_model_source_commit_id_commit', 'model', 'commit', ['source_commit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_loop_project_id_project', 'loop', type_='foreignkey')
    op.drop_constraint('fk_loop_last_confirmed_commit_id_commit', 'loop', type_='foreignkey')
    op.drop_constraint('fk_loop_branch_id_branch', 'loop', type_='foreignkey')
    op.drop_constraint('fk_loop_active_snapshot_version_id_loop_snapshot_version', 'loop', type_='foreignkey')
    op.drop_constraint('fk_loop_snapshot_version_24991dae', 'loop_snapshot_version', type_='foreignkey')
    op.drop_constraint('fk_loop_snapshot_version_created_by_user', 'loop_snapshot_version', type_='foreignkey')
    op.drop_constraint('fk_loop_snapshot_version_loop_id_loop', 'loop_snapshot_version', type_='foreignkey')
    op.drop_constraint('fk_round_project_id_project', 'round', type_='foreignkey')
    op.drop_constraint('fk_round_retry_of_round_id_round', 'round', type_='foreignkey')
    op.drop_constraint('fk_round_loop_id_loop', 'round', type_='foreignkey')
    op.drop_constraint('fk_round_input_commit_id_commit', 'round', type_='foreignkey')
    op.drop_constraint('fk_model_parent_model_id_model', 'model', type_='foreignkey')
    op.drop_constraint('fk_model_source_round_id_round', 'model', type_='foreignkey')
    op.drop_constraint('fk_model_project_id_project', 'model', type_='foreignkey')
    op.drop_constraint('fk_model_created_by_user', 'model', type_='foreignkey')
    op.drop_constraint('fk_model_source_task_id_task', 'model', type_='foreignkey')
    op.drop_constraint('fk_model_source_commit_id_commit', 'model', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_item_rank'), table_name='prediction_item')
    op.drop_index(op.f('ix_prediction_item_label_id'), table_name='prediction_item')
    op.drop_table('prediction_item')
    op.drop_index(op.f('ix_prediction_binding_schema_hash'), table_name='prediction_binding')
    op.drop_index(op.f('ix_prediction_binding_prediction_id'), table_name='prediction_binding')
    op.drop_index(op.f('ix_prediction_binding_model_id'), table_name='prediction_binding')
    op.drop_table('prediction_binding')
    op.drop_index(op.f('ix_prediction_task_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_status'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_scope_type'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_project_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_plugin_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_model_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_created_by'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_base_commit_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_model_class_schema_schema_hash'), table_name='model_class_schema')
    op.drop_index(op.f('ix_model_class_schema_model_id'), table_name='model_class_schema')
    op.drop_index(op.f('ix_model_class_schema_label_id'), table_name='model_class_schema')
    op.drop_index(op.f('ix_model_class_schema_class_index'), table_name='model_class_schema')
    op.drop_table('model_class_schema')
    op.drop_index(op.f('ix_commit_annotation_map_sample_id'), table_name='commit_annotation_map')
    op.drop_index(op.f('ix_commit_annotation_map_project_id'), table_name='commit_annotation_map')
    op.drop_index(op.f('ix_commit_annotation_map_commit_id'), table_name='commit_annotation_map')
    op.drop_index(op.f('ix_commit_annotation_map_annotation_id'), table_name='commit_annotation_map')
    op.drop_index('idx_commit_sample_lookup', table_name='commit_annotation_map')
    op.drop_table('commit_annotation_map')
    op.drop_index(op.f('ix_task_metric_point_ts'), table_name='task_metric_point')
    op.drop_index(op.f('ix_task_metric_point_task_id'), table_name='task_metric_point')
    op.drop_index(op.f('ix_task_metric_point_step'), table_name='task_metric_point')
    op.drop_index(op.f('ix_task_metric_point_metric_name'), table_name='task_metric_point')
    op.drop_index(op.f('ix_task_metric_point_epoch'), table_name='task_metric_point')
    op.drop_table('task_metric_point')
    op.drop_index(op.f('ix_task_event_ts'), table_name='task_event')
    op.drop_index(op.f('ix_task_event_task_id'), table_name='task_event')
    op.drop_index(op.f('ix_task_event_seq'), table_name='task_event')
    op.drop_index(op.f('ix_task_event_event_type'), table_name='task_event')
    op.drop_table('task_event')
    op.drop_index(op.f('ix_task_dispatch_outbox_task_id'), table_name='task_dispatch_outbox')
    op.drop_index('ix_task_dispatch_outbox_status_next_attempt_at', table_name='task_dispatch_outbox')
    op.drop_index(op.f('ix_task_dispatch_outbox_request_id'), table_name='task_dispatch_outbox')
    op.drop_table('task_dispatch_outbox')
    op.drop_index(op.f('ix_task_candidate_item_task_id'), table_name='task_candidate_item')
    op.drop_index(op.f('ix_task_candidate_item_sample_id'), table_name='task_candidate_item')
    op.drop_table('task_candidate_item')
    op.drop_index(op.f('ix_step_task_id'), table_name='step')
    op.drop_index(op.f('ix_step_step_type'), table_name='step')
    op.drop_index(op.f('ix_step_step_index'), table_name='step')
    op.drop_index(op.f('ix_step_state'), table_name='step')
    op.drop_index(op.f('ix_step_round_index'), table_name='step')
    op.drop_index(op.f('ix_step_round_id'), table_name='step')
    op.drop_index(op.f('ix_step_input_commit_id'), table_name='step')
    op.drop_index(op.f('ix_step_dispatch_kind'), table_name='step')
    op.drop_index(op.f('ix_step_assigned_executor_id'), table_name='step')
    op.drop_table('step')
    op.drop_index(op.f('ix_round_selection_override_sample_id'), table_name='round_selection_override')
    op.drop_index(op.f('ix_round_selection_override_round_id'), table_name='round_selection_override')
    op.drop_index(op.f('ix_round_selection_override_op'), table_name='round_selection_override')
    op.drop_index(op.f('ix_round_selection_override_created_by'), table_name='round_selection_override')
    op.drop_table('round_selection_override')
    op.drop_index(op.f('ix_model_source_task_id'), table_name='model')
    op.drop_index(op.f('ix_model_source_round_id'), table_name='model')
    op.drop_index(op.f('ix_model_source_commit_id'), table_name='model')
    op.drop_index(op.f('ix_model_project_id'), table_name='model')
    op.drop_index(op.f('ix_model_plugin_id'), table_name='model')
    op.drop_index(op.f('ix_model_parent_model_id'), table_name='model')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_model_arch'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_loop_snapshot_sample_partition'), table_name='loop_snapshot_sample')
    op.drop_index(op.f('ix_loop_snapshot_sample_locked'), table_name='loop_snapshot_sample')
    op.drop_index(op.f('ix_loop_snapshot_sample_cohort_index'), table_name='loop_snapshot_sample')
    op.drop_table('loop_snapshot_sample')
    op.drop_index(op.f('ix_loop_sample_state_visible_in_train'), table_name='loop_sample_state')
    op.drop_index(op.f('ix_loop_sample_state_source'), table_name='loop_sample_state')
    op.drop_index(op.f('ix_loop_sample_state_revealed_round_index'), table_name='loop_sample_state')
    op.drop_index(op.f('ix_loop_sample_state_reveal_commit_id'), table_name='loop_sample_state')
    op.drop_table('loop_sample_state')
    op.drop_index(op.f('ix_commit_sample_state_state'), table_name='commit_sample_state')
    op.drop_index(op.f('ix_commit_sample_state_sample_id'), table_name='commit_sample_state')
    op.drop_index(op.f('ix_commit_sample_state_project_id'), table_name='commit_sample_state')
    op.drop_index(op.f('ix_commit_sample_state_commit_id'), table_name='commit_sample_state')
    op.drop_index('idx_commit_sample_state_lookup', table_name='commit_sample_state')
    op.drop_table('commit_sample_state')
    op.drop_index(op.f('ix_annotation_draft_user_id'), table_name='annotation_draft')
    op.drop_index(op.f('ix_annotation_draft_sample_id'), table_name='annotation_draft')
    op.drop_index(op.f('ix_annotation_draft_project_id'), table_name='annotation_draft')
    op.drop_index(op.f('ix_annotation_draft_branch_name'), table_name='annotation_draft')
    op.drop_table('annotation_draft')
    op.drop_index(op.f('ix_annotation_type'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_source'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_sample_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_project_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_parent_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_lineage_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_label_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_group_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_confidence'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_index(op.f('ix_task_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_plugin_id'), table_name='task')
    op.drop_index(op.f('ix_task_kind'), table_name='task')
    op.drop_index(op.f('ix_task_input_commit_id'), table_name='task')
    op.drop_index(op.f('ix_task_assigned_executor_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_sample_name'), table_name='sample')
    op.drop_index(op.f('ix_sample_dataset_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_index(op.f('ix_round_state'), table_name='round')
    op.drop_index(op.f('ix_round_round_index'), table_name='round')
    op.drop_index(op.f('ix_round_project_id'), table_name='round')
    op.drop_index(op.f('ix_round_plugin_id'), table_name='round')
    op.drop_index(op.f('ix_round_loop_id'), table_name='round')
    op.drop_index(op.f('ix_round_confirmed_at'), table_name='round')
    op.drop_index(op.f('ix_round_attempt_index'), table_name='round')
    op.drop_index(op.f('ix_round_assigned_executor_id'), table_name='round')
    op.drop_table('round')
    op.drop_table('project_dataset')
    op.drop_index(op.f('ix_branch_project_id'), table_name='branch')
    op.drop_index(op.f('ix_branch_name'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_user_system_role_user_id'), table_name='user_system_role')
    op.drop_index(op.f('ix_user_system_role_updated_by'), table_name='user_system_role')
    op.drop_index(op.f('ix_user_system_role_role_id'), table_name='user_system_role')
    op.drop_index(op.f('ix_user_system_role_created_by'), table_name='user_system_role')
    op.drop_table('user_system_role')
    op.drop_index(op.f('ix_system_setting_updated_by'), table_name='system_setting')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_resource_member_user_id'), table_name='resource_member')
    op.drop_index(op.f('ix_resource_member_updated_by'), table_name='resource_member')
    op.drop_index(op.f('ix_resource_member_resource_type'), table_name='resource_member')
    op.drop_index(op.f('ix_resource_member_resource_id'), table_name='resource_member')
    op.drop_index(op.f('ix_resource_member_created_by'), table_name='resource_member')
    op.drop_table('resource_member')
    op.drop_index(op.f('ix_label_project_id'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_import_task_event_ts'), table_name='import_task_event')
    op.drop_index(op.f('ix_import_task_event_task_id'), table_name='import_task_event')
    op.drop_index(op.f('ix_import_task_event_seq'), table_name='import_task_event')
    op.drop_index(op.f('ix_import_task_event_event_type'), table_name='import_task_event')
    op.drop_table('import_task_event')
    op.drop_index(op.f('ix_dataset_owner_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_commit_project_id'), table_name='commit')
    op.drop_index(op.f('ix_commit_parent_id'), table_name='commit')
    op.drop_index(op.f('ix_commit_commit_hash'), table_name='commit')
    op.drop_index(op.f('ix_commit_author_type'), table_name='commit')
    op.drop_table('commit')
    op.drop_index(op.f('ix_audit_log_updated_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_runtime_executor_stats_ts'), table_name='runtime_executor_stats')
    op.drop_table('runtime_executor_stats')
    op.drop_index(op.f('ix_runtime_executor_status'), table_name='runtime_executor')
    op.drop_index(op.f('ix_runtime_executor_last_seen_at'), table_name='runtime_executor')
    op.drop_index(op.f('ix_runtime_executor_is_online'), table_name='runtime_executor')
    op.drop_index(op.f('ix_runtime_executor_executor_id'), table_name='runtime_executor')
    op.drop_index(op.f('ix_runtime_executor_current_task_id'), table_name='runtime_executor')
    op.drop_table('runtime_executor')
    op.drop_index(op.f('ix_runtime_command_log_status'), table_name='runtime_command_log')
    op.drop_index(op.f('ix_runtime_command_log_command_id'), table_name='runtime_command_log')
    op.drop_table('runtime_command_log')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_loop_snapshot_version_version_index'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_val_policy'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_update_mode'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_parent_version_id'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_manifest_hash'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_loop_id'), table_name='loop_snapshot_version')
    op.drop_index(op.f('ix_loop_snapshot_version_created_by'), table_name='loop_snapshot_version')
    op.drop_table('loop_snapshot_version')
    op.drop_index(op.f('ix_loop_project_id'), table_name='loop')
    op.drop_index(op.f('ix_loop_phase'), table_name='loop')
    op.drop_index(op.f('ix_loop_mode'), table_name='loop')
    op.drop_index(op.f('ix_loop_lifecycle'), table_name='loop')
    op.drop_index(op.f('ix_loop_last_confirmed_commit_id'), table_name='loop')
    op.drop_index(op.f('ix_loop_branch_id'), table_name='loop')
    op.drop_index(op.f('ix_loop_active_snapshot_version_id'), table_name='loop')
    op.drop_table('loop')
    op.drop_index(op.f('ix_import_task_user_id'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_status'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_started_at'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_resource_type'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_resource_id'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_mode'), table_name='import_task')
    op.drop_index(op.f('ix_import_task_finished_at'), table_name='import_task')
    op.drop_table('import_task')
    op.drop_index(op.f('ix_asset_hash'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
