/**
 * AnnotationSidebar Component
 *
 * 标注工作空间的侧边栏组件
 */

import React from 'react';
import {Button, Card, List, Tag, Typography} from 'antd';
import {useTranslation} from 'react-i18next';
import {
    BorderOutlined,
    CheckOutlined,
    DeleteOutlined,
    LeftOutlined,
    RightOutlined,
    RotateRightOutlined,
} from '@ant-design/icons';
import {Annotation} from '../../types';

const {Title} = Typography;

export interface AnnotationSidebarProps {
    // Annotations
    annotations: Annotation[];
    selectedId: string | null;
    onAnnotationSelect: (id: string) => void;
    onAnnotationDelete: (id: string) => void;

    // Navigation
    currentIndex: number;
    totalSamples: number;
    onPrev: () => void;
    onNext: () => void;

    // Submit
    onSubmit: () => void;
    submitLabel?: string;

    // Custom render for annotation item (optional, for FEDO to show extra info)
    renderAnnotationItem?: (annotation: Annotation, index: number) => React.ReactNode;

    // Permission control
    currentUserId?: string;
    canEditAnnotation?: (annotation: Annotation) => boolean;
    hasAnyEditPermission?: boolean;
}

export const AnnotationSidebar: React.FC<AnnotationSidebarProps> = ({
                                                                        annotations,
                                                                        selectedId,
                                                                        onAnnotationSelect,
                                                                        onAnnotationDelete,
                                                                        currentIndex,
                                                                        totalSamples,
                                                                        onPrev,
                                                                        onNext,
                                                                        onSubmit,
                                                                        submitLabel,
                                                                        renderAnnotationItem,
                                                                        currentUserId,
                                                                        canEditAnnotation,
                                                                        hasAnyEditPermission = true,
                                                                    }) => {
    const {t} = useTranslation();

    const defaultRenderItem = (item: Annotation, index: number) => {
        // 检查是否可以编辑此标注
        const canEdit = canEditAnnotation ? canEditAnnotation(item) : hasAnyEditPermission;
        // 判断标注来源
        const isAutoGenerated =
            item.source === 'auto' ||
            item.source === 'system' ||
            item.source === 'model' ||
            item.source === 'fedo_mapping';
        // 如果没有 annotatorId 或等于当前用户 ID，则认为是自己的标注
        const isMine = item.annotatorId && item.annotatorId === currentUserId;

        return (
            <List.Item
                actions={canEdit && !isAutoGenerated ? [
                    <Button
                        type="text"
                        danger
                        icon={<DeleteOutlined/>}
                        onClick={(e: React.MouseEvent) => {
                            e.stopPropagation();
                            onAnnotationDelete(item.id);
                        }}
                    />,
                ] : []}
                className={`cursor-pointer border-l-[4px] px-4 py-2 ${
                    selectedId === item.id ? 'bg-[var(--github-selected-bg)]' : 'bg-transparent'
                } ${canEdit ? 'opacity-100' : 'opacity-70'}`}
                style={{
                    borderLeftColor:
                        selectedId === item.id
                            ? item.labelColor || '#1890ff'
                            : 'transparent',
                }}
                onClick={() => onAnnotationSelect(item.id)}
            >
                <div className="flex w-full flex-col">
                    <div className="flex flex-wrap items-center gap-2">
                        {item.type === 'obb' ? <RotateRightOutlined/> : <BorderOutlined/>}
                        <Tag color={item.labelColor}>{item.labelName}</Tag>
                        <span>#{index + 1}</span>
                    </div>
                    {/* 显示标注来源信息 */}
                    <span className="text-[11px] text-github-muted">
            {isAutoGenerated
                ? t('annotation.workspace.annotationSource.auto')
                : isMine
                    ? t('annotation.workspace.annotationSource.mine')
                    : t('annotation.workspace.annotationSource.others')}
                        {!canEdit && !isAutoGenerated && (
                            <Tag color="orange" className="ml-1 text-[10px]">
                                {t('annotation.workspace.readOnly')}
                            </Tag>
                        )}
          </span>
                </div>
            </List.Item>
        );
    };

    return (
        <aside className="w-[300px] shrink-0 overflow-y-auto border-l border-github-border bg-github-panel p-5 text-github-text">
            <Title level={4} className="!text-github-text">{t('annotation.workspace.annotations')}</Title>
            <div className="flex w-full flex-col gap-4">
                <Card size="small" className="[&_.ant-card-body]:p-0">
                    <List
                        size="small"
                        dataSource={annotations}
                        renderItem={(item, index) =>
                            renderAnnotationItem
                                ? renderAnnotationItem(item, index)
                                : defaultRenderItem(item, index)
                        }
                    />
                    {annotations.length === 0 && (
                        <div className="p-4 text-center text-github-muted">
                            {t('annotation.workspace.noAnnotations')}
                        </div>
                    )}
                </Card>

                <div className="mt-5">
                    <div className="flex items-center gap-2">
                        <Button
                            icon={<LeftOutlined/>}
                            onClick={onPrev}
                            disabled={currentIndex === 0}
                        />
                        <span>
              {currentIndex + 1} / {totalSamples}
            </span>
                        <Button
                            icon={<RightOutlined/>}
                            onClick={onNext}
                            disabled={currentIndex === totalSamples - 1}
                        />
                    </div>
                </div>

                <Button
                    type="primary"
                    block
                    icon={<CheckOutlined/>}
                    onClick={onSubmit}
                    className="mt-5"
                    disabled={!hasAnyEditPermission}
                    title={!hasAnyEditPermission ? t('annotation.workspace.noEditPermission') : undefined}
                >
                    {submitLabel || t('annotation.workspace.submitNext')}
                </Button>
            </div>
        </aside>
    );
};
