/**
 * AnnotationSidebar Component
 * 
 * 标注工作空间的侧边栏组件
 */

import React from 'react';
import { Button, Card, Space, Typography, List, Tag } from 'antd';
import { useTranslation } from 'react-i18next';
import {
  LeftOutlined,
  RightOutlined,
  CheckOutlined,
  DeleteOutlined,
  BorderOutlined,
  RotateRightOutlined,
} from '@ant-design/icons';
import { Annotation } from '../../types';

const { Title } = Typography;

export interface AnnotationSidebarProps {
  // Annotations
  annotations: Annotation[];
  selectedId: string | null;
  onAnnotationSelect: (id: string) => void;
  onAnnotationDelete: (id: string) => void;
  
  // Navigation
  currentIndex: number;
  totalSamples: number;
  onPrev: () => void;
  onNext: () => void;
  
  // Submit
  onSubmit: () => void;
  
  // Custom render for annotation item (optional, for FEDO to show extra info)
  renderAnnotationItem?: (annotation: Annotation, index: number) => React.ReactNode;
  
  // Permission control
  currentUserId?: string;
  canEditAnnotation?: (annotation: Annotation) => boolean;
  hasAnyEditPermission?: boolean;
}

export const AnnotationSidebar: React.FC<AnnotationSidebarProps> = ({
  annotations,
  selectedId,
  onAnnotationSelect,
  onAnnotationDelete,
  currentIndex,
  totalSamples,
  onPrev,
  onNext,
  onSubmit,
  renderAnnotationItem,
  currentUserId,
  canEditAnnotation,
  hasAnyEditPermission = true,
}) => {
  const { t } = useTranslation();

  const defaultRenderItem = (item: Annotation, index: number) => {
    // 检查是否可以编辑此标注
    const canEdit = canEditAnnotation ? canEditAnnotation(item) : hasAnyEditPermission;
    // 判断标注来源
    const isAutoGenerated =
      item.source === 'auto' ||
      item.source === 'system' ||
      !!item.extra?.parent_id ||
      !!item.extra?.parentId;
    // 如果没有 annotatorId 或等于当前用户 ID，则认为是自己的标注
    const isMine = item.annotatorId && item.annotatorId === currentUserId;
    
    return (
      <List.Item
        actions={canEdit && !isAutoGenerated ? [
          <Button
            type="text"
            danger
            icon={<DeleteOutlined />}
            onClick={(e: React.MouseEvent) => {
              e.stopPropagation();
              onAnnotationDelete(item.id);
            }}
          />,
        ] : []}
        className={`cursor-pointer border-l-[4px] px-4 py-2 ${
          selectedId === item.id ? 'bg-[#e6f7ff]' : 'bg-transparent'
        } ${canEdit ? 'opacity-100' : 'opacity-70'}`}
        style={{
          borderLeftColor:
            selectedId === item.id
              ? item.labelColor || '#1890ff'
              : 'transparent',
        }}
        onClick={() => onAnnotationSelect(item.id)}
      >
        <Space direction="vertical" size={0} className="w-full">
          <Space>
            {item.type === 'obb' ? <RotateRightOutlined /> : <BorderOutlined />}
            <Tag color={item.labelColor}>{item.labelName}</Tag>
            <span>#{index + 1}</span>
          </Space>
          {/* 显示标注来源信息 */}
          <span className="text-[11px] text-[#999]">
            {isAutoGenerated 
              ? t('workspace.annotationSource.auto')
              : isMine 
                ? t('workspace.annotationSource.mine')
                : t('workspace.annotationSource.others')}
            {!canEdit && !isAutoGenerated && (
              <Tag color="orange" className="ml-1 text-[10px]">
                {t('workspace.readOnly')}
              </Tag>
            )}
          </span>
        </Space>
      </List.Item>
    );
  };

  return (
    <aside className="w-[300px] shrink-0 border-l border-[#f0f0f0] bg-white p-5 overflow-y-auto">
      <Title level={4}>{t('workspace.annotations')}</Title>
      <Space direction="vertical" className="w-full">
        <Card size="small" className="[&_.ant-card-body]:p-0">
          <List
            size="small"
            dataSource={annotations}
            renderItem={(item, index) =>
              renderAnnotationItem
                ? renderAnnotationItem(item, index)
                : defaultRenderItem(item, index)
            }
          />
          {annotations.length === 0 && (
            <div className="p-4 text-center text-[#999]">
              {t('workspace.noAnnotations')}
            </div>
          )}
        </Card>

        <div className="mt-5">
          <Space>
            <Button
              icon={<LeftOutlined />}
              onClick={onPrev}
              disabled={currentIndex === 0}
            />
            <span>
              {currentIndex + 1} / {totalSamples}
            </span>
            <Button
              icon={<RightOutlined />}
              onClick={onNext}
              disabled={currentIndex === totalSamples - 1}
            />
          </Space>
        </div>

        <Button
          type="primary"
          block
          icon={<CheckOutlined />}
          onClick={onSubmit}
          className="mt-5"
          disabled={!hasAnyEditPermission}
          title={!hasAnyEditPermission ? t('workspace.noEditPermission') : undefined}
        >
          {t('workspace.submitNext')}
        </Button>
      </Space>
    </aside>
  );
};
