/**
 * AnnotationSidebar Component
 *
 * 标注工作空间的侧边栏组件
 */

import React, {useMemo} from 'react';
import {Button, Card, Tag, Typography} from 'antd';
import {useTranslation} from 'react-i18next';
import {
    BorderOutlined,
    CheckOutlined,
    DeleteOutlined,
    LeftOutlined,
    RightOutlined,
    RotateRightOutlined,
} from '@ant-design/icons';
import {Annotation, ANNOTATION_TYPE_OBB} from '../../types';
import {
    formatSidebarGeometrySummary,
    resolveSidebarAnnotationType,
    resolveSidebarAnnotationView,
    sortAnnotationsForSidebar,
} from '../../utils/annotationList';
import {formatConfidence, isConfidenceVisibleSource} from '../../utils/annotationConfidence';

const {Title} = Typography;

export interface AnnotationSidebarProps {
    // Annotations
    annotations: Annotation[];
    selectedId: string | null;
    selectedIds?: Set<string>;
    onAnnotationSelect: (id: string) => void;
    onAnnotationDelete: (id: string) => void;

    // Navigation
    currentIndex: number;
    totalSamples: number;
    onPrev: () => void;
    onNext: () => void;

    // Submit
    onSubmit: () => void;
    submitLabel?: string;

    // Custom render for annotation item (optional, for FEDO to show extra info)
    renderAnnotationItem?: (annotation: Annotation, index: number) => React.ReactNode;

    // Permission control
    currentUserId?: string;
    canEditAnnotation?: (annotation: Annotation) => boolean;
    hasAnyEditPermission?: boolean;
}

export const AnnotationSidebar: React.FC<AnnotationSidebarProps> = ({
                                                                        annotations,
                                                                        selectedId,
                                                                        selectedIds,
                                                                        onAnnotationSelect,
                                                                        onAnnotationDelete,
                                                                        currentIndex,
                                                                        totalSamples,
                                                                        onPrev,
                                                                        onNext,
                                                                        onSubmit,
                                                                        submitLabel,
                                                                        renderAnnotationItem,
                                                                        canEditAnnotation,
                                                                        hasAnyEditPermission = true,
                                                                    }) => {
    const {t} = useTranslation();
    const sortedAnnotations = useMemo(() => sortAnnotationsForSidebar(annotations as any[]), [annotations]);

    const defaultRenderItem = (item: Annotation) => {
        // 检查是否可以编辑此标注
        const canEdit = canEditAnnotation ? canEditAnnotation(item) : hasAnyEditPermission;
        // 判断标注来源
        const isAutoGenerated =
            item.source === 'auto' ||
            item.source === 'system' ||
            item.source === 'fedo_mapping';
        const source = String(item.source || 'manual');
        const sourceLabel = ({
            manual: t('annotation.workspace.annotationSource.manual'),
            auto: t('annotation.workspace.annotationSource.auto'),
            model: t('annotation.workspace.annotationSource.model'),
            confirmed_model: t('annotation.workspace.annotationSource.confirmedModel'),
            system: t('annotation.workspace.annotationSource.system'),
            imported: t('annotation.workspace.annotationSource.imported'),
            fedo_mapping: t('annotation.workspace.annotationSource.fedoMapping'),
        } as Record<string, string>)[source] || source;
        const annType = resolveSidebarAnnotationType(item as any);
        const view = resolveSidebarAnnotationView(item as any);
        const geometrySummary = formatSidebarGeometrySummary(item as any);
        const confidenceText = isConfidenceVisibleSource(source)
            ? formatConfidence((item as any)?.confidence)
            : null;
        const rawMappedCount =
            (item as any)?.attrs?.mapped_count ??
            (item as any)?.secondary?.regions?.length;
        const mappedCount =
            Number.isFinite(Number(rawMappedCount)) && Number(rawMappedCount) >= 0
                ? Math.floor(Number(rawMappedCount))
                : null;
        const isSelected = selectedIds ? selectedIds.has(item.id) : selectedId === item.id;
        const canShowDelete = canEdit && !isAutoGenerated;
        const shapeLabel =
            annType === ANNOTATION_TYPE_OBB
                ? t('annotation.workspace.annotationShape.obb')
                : t('annotation.workspace.annotationShape.rect');
        const viewLabel =
            view === 'time-energy'
                ? t('annotation.workspace.annotationView.timeEnergy')
                : view === 'L-omegad'
                    ? t('annotation.workspace.annotationView.lOmegad')
                    : view;

        return (
            <div
                className={`group relative cursor-pointer border-l-[3px] px-3 py-2 transition-colors ${
                    isSelected ? 'bg-[var(--github-selected-bg)]' : 'bg-transparent hover:bg-[var(--github-hover-bg)]'
                } ${canEdit ? 'opacity-100' : 'opacity-70'}`}
                style={{
                    borderLeftColor: isSelected ? item.labelColor || '#1890ff' : 'transparent',
                }}
                onClick={() => onAnnotationSelect(item.id)}
                title={item.id}
            >
                {canShowDelete ? (
                    <Button
                        type="text"
                        danger
                        size="small"
                        icon={<DeleteOutlined/>}
                        className="!absolute !right-1 !top-1 !h-6 !w-6 !min-w-0 !p-0 opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100"
                        onClick={(e: React.MouseEvent) => {
                            e.stopPropagation();
                            onAnnotationDelete(item.id);
                        }}
                    />
                ) : null}
                <div className="flex items-center gap-2">
                    <span className="text-github-muted">
                        {annType === ANNOTATION_TYPE_OBB ? <RotateRightOutlined/> : <BorderOutlined/>}
                    </span>
                    <Tag color={item.labelColor} className="!m-0">
                        {item.labelName}
                    </Tag>
                    <span className="text-[11px] text-github-muted">{shapeLabel}</span>
                    {viewLabel ? <span className="text-[11px] text-github-muted">{viewLabel}</span> : null}
                    <span className={`text-[10px] ${isAutoGenerated ? 'text-purple-400' : 'text-github-muted'}`}>
                        {sourceLabel}
                    </span>
                    {confidenceText !== null ? (
                        <span className="text-[10px] text-github-muted">
                            {t('annotation.workspace.confidenceShort', {confidence: confidenceText})}
                        </span>
                    ) : null}
                    {mappedCount !== null ? (
                        <span className="text-[10px] text-github-muted">
                            {t('annotation.workspace.annotationMeta.mappedCount', {count: mappedCount})}
                        </span>
                    ) : null}
                    {!canEdit && !isAutoGenerated ? (
                        <span className="text-[10px] text-orange-400">{t('annotation.workspace.readOnly')}</span>
                    ) : null}
                </div>
                <span className="mt-1 block truncate text-[11px] text-github-muted">
                    {geometrySummary || t('annotation.workspace.annotationMeta.unavailable')}
                </span>
            </div>
        );
    };

    return (
        <aside className="w-[300px] shrink-0 overflow-y-auto border-l border-github-border bg-github-panel p-5 text-github-text">
            <Title level={4} className="!text-github-text">{t('annotation.workspace.annotations')}</Title>
            <div className="flex w-full flex-col gap-4">
                <Card size="small" className="[&_.ant-card-body]:p-0">
                    {sortedAnnotations.length > 0 && (
                        <div className="border-b border-github-border px-3 py-2 text-[11px] text-github-muted">
                            {t('annotation.workspace.annotationOrderHint')}
                        </div>
                    )}
                    {sortedAnnotations.map((item, index) => (
                        <div key={item.id} className="border-b border-github-border last:border-b-0">
                            {renderAnnotationItem ? renderAnnotationItem(item, index) : defaultRenderItem(item)}
                        </div>
                    ))}
                    {annotations.length === 0 && (
                        <div className="p-4 text-center text-github-muted">
                            {t('annotation.workspace.noAnnotations')}
                        </div>
                    )}
                </Card>

                <div className="mt-5">
                    <div className="flex items-center gap-2">
                        <Button
                            icon={<LeftOutlined/>}
                            onClick={onPrev}
                            disabled={currentIndex === 0}
                        />
                        <span>
              {currentIndex + 1} / {totalSamples}
            </span>
                        <Button
                            icon={<RightOutlined/>}
                            onClick={onNext}
                            disabled={currentIndex === totalSamples - 1}
                        />
                    </div>
                </div>

                <Button
                    type="primary"
                    block
                    icon={<CheckOutlined/>}
                    onClick={onSubmit}
                    className="mt-5"
                    disabled={!hasAnyEditPermission}
                    title={!hasAnyEditPermission ? t('annotation.workspace.noEditPermission') : undefined}
                >
                    {submitLabel || t('annotation.workspace.submitNext')}
                </Button>
            </div>
        </aside>
    );
};
