from __future__ import annotations

from saki_ir.codec import decode_payload, decompress_raw, encode_payload, iter_items, read_header, verify_checksum
from saki_ir.convert import (
    ConversionContext,
    ConversionError,
    ConversionReport,
    coco_to_ir,
    ir_to_coco,
    ir_to_voc_xml,
    ir_to_yolo_txt,
    ir_to_yolo_obb_txt,
    voc_xml_to_ir,
    yolo_obb_txt_to_ir,
    yolo_txt_to_ir,
)
from saki_ir.convert.io import (
    load_coco_dataset,
    load_voc_dataset,
    load_yolo_dataset,
    save_coco_dataset,
    save_voc_dataset,
    save_yolo_dataset,
)
from saki_ir.dataframe import to_dataframe
from saki_ir.format_profiles import (
    FormatProfile,
    FormatProfileId,
    filter_profiles_by_annotation_types,
    get_format_profile,
    list_format_profiles,
)
from saki_ir.normalize import normalize_ir, validate_ir
from saki_ir.selector import selector_cardinality, selector_checksum, validate_manifest_selector
from saki_ir.transport import (
    ChunkAssembler,
    CompletedPayloadCache,
    PayloadChunk,
    parse_header,
    serialize_header,
    split_encoded_payload,
)
from saki_ir.view import AnnotationView, BatchView, EncodedPayloadView, GeometryView, ObbView, RectView
from saki_ir.proto.saki.ir.v1.annotation_ir_pb2 import (  # noqa: F401
    AnnotationRecord,
    AnnotationSource,
    DataBatchIR,
    DataItemIR,
    EncodedPayload,
    Geometry,
    LabelRecord,
    ObbGeometry,
    PayloadChecksumAlgo,
    PayloadCodec,
    PayloadCompression,
    PayloadHeader,
    PayloadSchema,
    PayloadStats,
    RectGeometry,
    SampleRecord,
)
from saki_ir.proto.saki.ir.v1.dataset_manifest_ir_pb2 import (  # noqa: F401
    BitsetSelector,
    DatasetManifestIR,
    DatasetSplitManifestIR,
    ManifestSelector,
    ManifestSelectorEncoding,
    OrdinalRange,
    RangeSelector,
    RoaringSelector,
    RoundManifestBundleIR,
)

__all__ = [
    "normalize_ir",
    "validate_ir",
    "encode_payload",
    "decode_payload",
    "decompress_raw",
    "verify_checksum",
    "read_header",
    "iter_items",
    "selector_cardinality",
    "selector_checksum",
    "validate_manifest_selector",
    "to_dataframe",
    "FormatProfileId",
    "FormatProfile",
    "list_format_profiles",
    "get_format_profile",
    "filter_profiles_by_annotation_types",
    "serialize_header",
    "parse_header",
    "split_encoded_payload",
    "PayloadChunk",
    "ChunkAssembler",
    "CompletedPayloadCache",
    "ConversionContext",
    "ConversionError",
    "ConversionReport",
    "coco_to_ir",
    "ir_to_coco",
    "voc_xml_to_ir",
    "ir_to_voc_xml",
    "yolo_txt_to_ir",
    "ir_to_yolo_txt",
    "yolo_obb_txt_to_ir",
    "ir_to_yolo_obb_txt",
    "load_coco_dataset",
    "save_coco_dataset",
    "load_voc_dataset",
    "save_voc_dataset",
    "load_yolo_dataset",
    "save_yolo_dataset",
    "EncodedPayloadView",
    "BatchView",
    "AnnotationView",
    "GeometryView",
    "RectView",
    "ObbView",
    "DataBatchIR",
    "DataItemIR",
    "LabelRecord",
    "SampleRecord",
    "AnnotationRecord",
    "Geometry",
    "RectGeometry",
    "ObbGeometry",
    "AnnotationSource",
    "PayloadSchema",
    "PayloadCodec",
    "PayloadCompression",
    "PayloadChecksumAlgo",
    "PayloadStats",
    "PayloadHeader",
    "EncodedPayload",
    "ManifestSelectorEncoding",
    "OrdinalRange",
    "RangeSelector",
    "RoaringSelector",
    "BitsetSelector",
    "ManifestSelector",
    "DatasetManifestIR",
    "DatasetSplitManifestIR",
    "RoundManifestBundleIR",
]
